services:
    avro_stripe.plan.manager:
        class: Avro\StripeBundle\Doctrine\PlanManager
        arguments: ["@doctrine.odm.mongodb.document_manager", "@event_dispatcher", "%avro_stripe.plan.class%"]



