services:
    avro_stripe.plan.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ['avro_stripe_plan', '@avro_stripe.plan.form.type']
        scope: request

    avro_stripe.plan.form.type:
        class: %avro_stripe.plan.form.class% 
        arguments: ['%avro_stripe.plan.class%']
        tags: 
            - { name: form.type, alias: avro_stripe_plan }


